languageCode = "en-us"

title = "PTO FTW"
theme = "tale"

[Author]
    name = "ptoftw"

[Params]
    author = "ptoftw"

[menu]
    [[menu.main]]
        identifier="motivation"
        name="Motivation"
        title="Motivation"
        url="/about/motivation"
        weight=0
